# Generated by Django 5.0 on 2024-03-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrecords',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
