# Generated by Django 5.0 on 2024-03-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customerdeletedrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdeletedrecords',
            old_name='created_at',
            new_name='deleted_at',
        ),
    ]
